=== manoj-pillay-10gen/simple-search-index-validator/schema/components/baseIndex.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "components/baseIndex.json",
  "type": "object",
  "description": "Define your Atlas Search Index",
  "properties": {
    "mappings": {
      "suggestSortText": "0",
      "$ref": "mappings.json"
    },
    "synonyms": {
      "suggestSortText": "4",
      "$ref": "synonyms.json"
    },
    "analyzer": {
      "suggestSortText": "2",
      "$ref": "common.json#/definitions/analyzers",
      "markdownDescription": "[Analyzer](https://dochub.mongodb.org/core/analyzers-fts) to apply on fields when indexing. If you omit this parameter, it defaults to the [Standard Analyzer](https://dochub.mongodb.org/core/standard-fts). Atlas Search applies this analyzer to all fields unless you specify a different analyzer in the field mapping definition.",
      "description": "Analyzer to apply to string fields when indexing."
    },
    "searchAnalyzer": {
      "suggestSortText": "3",
      "$ref": "common.json#/definitions/analyzers",
      "markdownDescription": "[Analyzer](https://dochub.mongodb.org/core/analyzers-fts) to apply to query text before searching with it. If you omit this parameter, it defaults to the analyzer that you specify for the `analyzer` option. If you omit both the `searchAnalyzer` and the `analyzer` options, it defaults to the [Standard Analyzer](https://dochub.mongodb.org/core/standard-fts).",
      "description": "Analyzer to apply to query text before searching with it."
    },
    "analyzers": {
      "suggestSortText": "1",
      "type": "array",
      "items": {
        "$ref": "custom_analyzer.json"
      },
      "markdownDescription": "[Custom analyzers](https://dochub.mongodb.org/core/custom-fts) to define for your index. You can define as many custom analyzers as you need for your specific indexing purposes.",
      "description": "Custom analyzers to define for your index.",
      "minItems": 1
    },
    "storedSource": {
      "suggestSortText": "5",
      "markdownDescription": "Boolean flag that indicates whether to store all the fields in your collection on Atlas Search or a Stored Source Object that specifies the fields to `include` or `exclude` from storage. If you omit this parameter, it defaults to `false`. To learn more, see [Define Stored Source Fields in Your Atlas Search Index](https://dochub.mongodb.org/core/stored-source-definition-fts).",
      "description": "Boolean flag that indicates whether to store the fields in your collection on Atlas Search or a Stored Source Object that specifies the fields to include or exclude from storage.",
      "examples": [
        {
          "include": [
            "<field_name_1>",
            "<field_name_2>"
          ]
        },
        {
          "exclude": [
            "<field_name_1>",
            "<field_name_2>"
          ]
        },
        false,
        true
      ],
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "include": {
              "type": "array",
              "markdownDescription": "List that contains the field names or dot-separated paths to the fields to store. By default, Atlas Search also stores the `_id` field.",
              "description": "List that contains the field names or paths to the fields to store.",
              "items": {
                "type": "string",
                "pattern": "^.*$",
                "errorMessage": "Field name does not meet MongoDb field naming restrictions. Please see https://www.mongodb.com/docs/manual/core/document/#field-names ."
              }
            },
            "exclude": {
              "type": "array",
              "markdownDescription": "List that contains the field names or dot-separated paths to the fields to exclude from storage.",
              "description": "List that contains the field names or paths to the fields to exclude from storage.",
              "items": {
                "type": "string",
                "pattern": "^.*$",
                "errorMessage": "Field name does not meet MongoDb field naming restrictions. Please see https://www.mongodb.com/docs/manual/core/document/#field-names ."
              }
            }
          },
          "additionalProperties": false
        },
        {
          "type": "boolean"
        }
      ]
    }
  }
}

=== manoj-pillay-10gen/simple-search-index-validator/data/sampleData/JSONEditorSamples/custom-analyzer/custom-analyzer-index-definition-21.json
{
  "mappings": {
    "dynamic": true
  },
  "analyzer": "builtinAnalyzer",
  "searchAnalyzer": "luceneAnalyzer",
  "analyzers": [
    {
      "name": "builtinAnalyzer",
      "tokenizer": {
        "type": "standard"
      },
      "tokenFilters": [
        {
          "type": "lowercase"
        }
      ]
    },
    {
      "name": "luceneAnalyzer",
      "tokenizer": {
        "type": "whitespace"
      },
      "charFilters": [
        {
          "type": "mapping",
          "mappings": {
            "a": ""
          }
        }
      ]
    }
  ]
}

=== manoj-pillay-10gen/simple-search-index-validator/data/sampleData/JSONEditorSamples/synonyms/synonyms-index-definition-06.json
{
  "mappings": {
    "dynamic": true
  },
  "analyzer": "normalizer",
  "synonyms": [
    {
      "name": "normalizedSynonyms",
      "source": {
        "collection": "collection"
      },
      "analyzer": "normalizer"
    }
  ],
  "analyzers": [
    {
      "name": "normalizer",
      "charFilters": [
        {
          "type": "icuNormalize"
        }
      ],
      "tokenizer": {
        "type": "standard"
      },
      "tokenFilters": []
    }
  ]
}

=== manoj-pillay-10gen/simple-search-index-validator/data/sampleData/JSONEditorSamples/synonyms/synonyms-index-definition-01.json
{
  "mappings": {
    "dynamic": true,
    "fields": {
      "b": {
        "type": "string",
        "analyzer": "englishStandardNormalizer"
      },
      "c": {
        "type": "string",
        "analyzer": "lucene.standard"
      }
    }
  },
  "analyzer": "lucene.whitespace",
  "synonyms": [
    {
      "name": "firstSynonyms",
      "source": {
        "collection": "coll1"
      },
      "analyzer": "lucene.whitespace"
    },
    {
      "name": "secondSynonyms",
      "source": {
        "collection": "coll2"
      },
      "analyzer": "englishStandardNormalizer"
    },
    {
      "name": "thirdSynonyms",
      "source": {
        "collection": "coll3"
      },
      "analyzer": "lucene.standard"
    }
  ],
  "analyzers": [
    {
      "name": "englishStandardNormalizer",
      "charFilters": [
        {
          "type": "icuNormalize"
        }
      ],
      "tokenizer": {
        "type": "standard"
      },
      "tokenFilters": [
        {
          "type": "icuFolding"
        },
        {
          "type": "snowballStemming",
          "stemmerName": "english"
        }
      ]
    }
  ]
}
